### ISSUE TITLE
Some sheep appear invisible

### ISSUE THREAD

**Issue by SinmisModdingCommunity** [SinmisModdingCommunity/The_Createville_Server#3]
Description: sheep sometimes only leave their shadows to appear

Steps to reproduce: idk look around for long enough?

Extras (picture, video or a crash report if it applies):

**Comment by Slipperyeire07** [comment]
![image](https://user-images.githubusercontent.com/121187431/222968395-437050b5-37d4-449b-a05f-1e54d99cc77f.png)
