### ISSUE TITLE
TINKERSSSSSSSSSSSSSSSSSSSSSSSSSSSS also adds more metals too mine and molten metals too work with meaning more pipelinessss

### ISSUE THREAD

**Issue by ImYepee** [SinmisModdingCommunity/The_Createville_Server#48]
https://www.curseforge.com/minecraft/mc-mods/tinkers-construct
https://www.curseforge.com/minecraft/mc-mods/tinkers-construct
https://www.curseforge.com/minecraft/mc-mods/tinkers-construct
https://www.curseforge.com/minecraft/mc-mods/tinkers-construct

plsplsplspls

**Comment by SinmisModdingCommunity** [comment]
Wont happen, doesn't exist for 1.19.2
