### ISSUE TITLE
Stoneling Map Drop - Bugged

### ISSUE THREAD

**Issue by Zand-MC** [SinmisModdingCommunity/The_Createville_Server#55]
Description: 
When the stoneling drops a map the location of the treasure is incredibly far away and since no-one has found the treasure all map drops lead to the same one.

Steps to reproduce: 
kill a stoneline for the map drop.

Extras (picture, video or a crash report if it applies):
![2023-04-02_19 10 25](https://user-images.githubusercontent.com/60796042/229386712-1bd25d26-570a-489f-ad56-e51d145fed7e.png)

**Comment by SinmisModdingCommunity** [comment]
Causes significant lag spikes when killed
