### ISSUE TITLE
Config request: Savage and Ravage - Ominous Banner burning 

### ISSUE THREAD

**Issue by rastrof** [SinmisModdingCommunity/The_Createville_Server#62]
A feature of the Savage and Ravage mod is to be able to burn a Ominous Banner to get the "Bad Omen" debuff for raids in villages.
Kindly enable this setting.

Context: https://www.minecraft-guides.com/mod/savage-and-ravage/

**Comment by SinmisModdingCommunity** [comment]
feature doesn't exist? if it does I couldn't find it in the configs
